name: Actions

on: [pull_request]

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform.platform }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            targetPlatform:
                - platform: StandaloneWindows64
                  buildDirectory: Windows
                  clientMethod: BuildScript.BuildWindowsClient
                  serverMethod: BuildScript.BuildWindowsServer
                - platform: StandaloneLinux64
                  buildDirectory: Linux
                  clientMethod: BuildScript.BuildLinuxClient
                  serverMethod: BuildScript.BuildLinuxServer
                - platform: StandaloneOSX
                  buildDirectory: Mac   
                  clientMethod: BuildScript.BuildMacClient
                  serverMethod: BuildScript.BuildMacServer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        
      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library files
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library-

      - name: Client ${{ matrix.targetPlatform.platform }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform.platform }}
          versioning: Semantic
          buildMethod: ${{ matrix.targetPlatform.clientMethod }}
          allowDirtyBuild: true     
          
      - name: Server ${{ matrix.targetPlatform.platform }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform.platform }}
          versioning: Semantic
          allowDirtyBuild: true
          buildMethod: ${{ matrix.targetPlatform.serverMethod }}
   
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform.platform }}
          path: Builds/${{ matrix.targetPlatform.buildDirectory }}
