name: Actions

on: 
  pull_request: 
  push:
    branches:
      - "master"
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/game-server

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform.platform }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            targetPlatform:
                - platform: StandaloneWindows64
                  buildDirectory: Windows
                  clientMethod: BuildScript.BuildWindowsClient
                  serverMethod: BuildScript.BuildWindowsServer
                - platform: StandaloneLinux64
                  buildDirectory: Linux
                  clientMethod: BuildScript.BuildLinuxClient
                  serverMethod: BuildScript.BuildLinuxServer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
        
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        
      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library files
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Client ${{ matrix.targetPlatform.platform }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform.platform }}
          versioning: Semantic
          buildMethod: ${{ matrix.targetPlatform.clientMethod }}
          allowDirtyBuild: true 

      - name: Upload Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client-${{ matrix.targetPlatform.platform }}
          path: Builds/${{ matrix.targetPlatform.buildDirectory }}/Client
          if-no-files-found: error
          
      - name: Server ${{ matrix.targetPlatform.platform }}
        if: ${{ matrix.targetPlatform.platform == 'StandaloneLinux64' }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform.platform }}
          versioning: Semantic
          allowDirtyBuild: true
          buildMethod: ${{ matrix.targetPlatform.serverMethod }}

      - name: Upload Server Artifact
        if: ${{ matrix.targetPlatform.platform == 'StandaloneLinux64' }}
        uses: actions/upload-artifact@v4
        with:
          name: Server-Linux64-DockerReady
          path: Builds/${{ matrix.targetPlatform.buildDirectory }}/Server
          if-no-files-found: error
  docker-push-server:
    name: Docker Push Linux Server
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile.server

      - name: Download Linux Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: Server-Linux64-DockerReady
          path: build_context

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_tag}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: build_context
          file: Dockerfile.server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  create-release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Windows Client
        uses: actions/download-artifact@v4
        with:
           name: Client-StandaloneWindows64
           path: clients/Windows

      - name: Download Linux Client
        uses: actions/download-artifact@v4
        with:
           name: Client-StandaloneLinux64
           path: clients/Linux

      - name: Zip Clients
        run: |
          cd clients/Windows && zip -r ../../WindowsClient.zip .
          cd ../../clients/Linux && zip -r ../../LinuxClient.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            WindowsClient.zip
            LinuxClient.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}